% This version is used to extract data from data file generated by WIPL-D
% software. It is applied for two variables only.

clc
clear

filepath = "E:\NAIST_Works\MIMO_CV";
file_to_read = "3x2_i_compensated_TXRX.cu1";
filepath_save = "E:\Dropbox\WPTProject\MIMO_CV";
filename_save = "testdata.xlsx";


file_fullpath = filepath + "\" + file_to_read

% fid=fopen(fullfile(filepath, file_to_read)); 
fid=fopen(file_fullpath); 

numwire = 5; % number of the wires whose currents need to be extracted
numvar1 = 10;
numvar2 = 10;
numconf = numvar1*numvar2; % number of configurations (loop)
var_chk = 'R4'; % variable changed in WIPL-D
cnt = 1;
cntvar1 = 1;

I_vector = [];
I_temp = [];



% filename_save = 'testdata.xlsx';
file_fullpath_save = filepath_save + "\" + filename_save
if isfile(file_fullpath_save)
%     delete testdata.xlsx
    delete(file_fullpath_save)
end


if fseek(fid, 1, 'bof') == -1 % empty file
   disp("file is empty");
else
   a = 1;
end

while a == 1
    A = fgetl(fid); % read one line in the file
    A_element = strsplit(A,' '); % split long string into elements
    if strcmp(A_element(2), var_chk)
        for wcnt = 1:numwire
            fgetl(fid);fgetl(fid);fgetl(fid); % ignore 3 lines
            I_array = fgetl(fid);
            I_element = strsplit(I_array,' '); % split long string into elements
            I_temp = [I_temp str2double(I_element(3)) str2double(I_element(4))]; % write data
            fgetl(fid);fgetl(fid); % ignore 3 lines
        end
        cnt = cnt + 1;
        cntvar1 = cntvar1 + 1;
    end
    I_vector = [I_vector;I_temp]; % store data into large matrix
    I_temp = [];
    if cntvar1 == numvar1+1 % to separate every numvar1 configuaration
        I_vector = [I_vector; zeros(1,numwire*2)];
        cntvar1 = 1;
    end
    if cnt > numconf
        break
    end
end

% I_vector

% generate array of load as variables in WIPL-D
step = 10;
R1 = []; 
for b = 1:numvar2
    for c = 1:numvar1
        R_temp = c*step;
        R1 =[R1;R_temp];
    end
    R1 = [R1;0]; % to separate every numvar1 configuaration
end
% R1;
R2 = []; 
for b = 1:numvar1
    R_temp = b*step;
    for c = 1:numvar2
        R2 =[R2;R_temp];
    end
    R2 = [R2;0]; % to separate every numvar1 configuaration
end
% R2;

R = [R1 R2];

A = {}; % containing the label of currents


for b = 1:numwire
    A{1,2*b-1} = "I" + string(b) +"-r";
    A{1,2*b} = "I" + string(b) +"-i";
end


B = {"|VR1|" "|VR2|"};  % containing the label of load voltages 

VR1_sim = sqrt(I_vector(:,7).^2+I_vector(:,8).^2)/1000.*R1;
VR2_sim = sqrt(I_vector(:,9).^2+I_vector(:,10).^2)/1000.*R2;
VR_sim = [VR1_sim VR2_sim];

writecell(A,file_fullpath_save, 'Sheet',1,'Range','A1');
writematrix(I_vector/1000,file_fullpath_save, 'Sheet',1,'Range','A2');
writecell(B,file_fullpath_save, 'Sheet',1,'Range','K1');
writematrix(VR_sim,file_fullpath_save, 'Sheet',1,'Range','K2');
writecell({"R1" "R2"},file_fullpath_save, 'Sheet',1,'Range','O1');
writematrix(R,file_fullpath_save, 'Sheet',1,'Range','O2');

fclose(fid);
fclose('all');