% This version is used to extract data from data file generated by WIPL-D
% software. It is applied for one variable only.

clc
clear


path = '..\..\WPT_research\Resonance';

filename = strcat(path,'Res2x2I_planar_200115.cu1');
fid=fopen(filename); 

numwire = 4; % number of the wires whose currents need to be extracted
numconf = 20; % number of configurations (loop)
var_chk = 'R'; % variable changed in WIPL-D
cnt = 1;

I_vector = [];
I_temp = [];

filename_save = 'testdata.xlsx';
if isfile(filename_save)
    delete testdata.xlsx
end


if fseek(fid, 1, 'bof') == -1 % empty file
   disp("file is empty");
else
   a = 1;
end

while a == 1
    A = fgetl(fid); % read one line in the file
    A_element = strsplit(A,' '); % split long string into elements
    if strcmp(A_element(2), var_chk)
        for wcnt = 1:numwire
            fgetl(fid);fgetl(fid);fgetl(fid); % ignore next 3 lines
            I_array = fgetl(fid);
            I_element = strsplit(I_array,' '); % split long string into elements
            I_temp = [I_temp str2double(I_element(3:4))]; % write data
            fgetl(fid);fgetl(fid); % ignore next 2 lines
        end
        cnt = cnt + 1;
    end
    I_vector = [I_vector;I_temp]; % store data into large matrix
    I_temp = [];
    if cnt > numconf
        break
    end
end

I_vector

writematrix(I_vector/1000,filename_save, 'Sheet',1,'Range','A1');
% writematrix(VR_sim,filename_save, 'Sheet',1,'Range','A20');

fclose(fid);
fclose('all');