% This version is used to extract data from data file generated by WIPL-D
% software. It is applied for two variables only.

clc
clear

% fid=fopen('..\..\..\..\WPT_research\CooperativeMultipleRelay\Sim_Cheng2019b\15turn_3terminal_I.cu1'); 
% fid=fopen('..\..\..\..\WPT_research\CooperativeMultipleRelay\Sim_proposed\3term_relay2coil_15turn.cu1');
% fid=fopen('..\..\..\..\WPT_research\CooperativeMultipleRelay\Sim_proposed\3term_relay1coil_15turn.cu1'); 
% fid=fopen('..\..\..\..\WPT_research\Smooth3coilSys\wires\15turn_threecoil_CLC_S.cu1');
fid=fopen('..\..\..\..\WPT_research\CooperativeMultipleRelay\Sim_proposed\3term_relay2coil_15turn_noM02.cu1');

numwire = 4; % number of the wires whose currents need to be extracted
numvar1 = 20;
numvar2 = 20;
numconf = numvar1*numvar2; % number of configurations (loop)
var_chk = 'R1'; % variable changed in WIPL-D
cnt = 1;
cntvar1 = 1;

I_vector = [];
I_temp = [];

filename_save = 'testdata.xlsx';
if isfile(filename_save)
    delete testdata.xlsx
end


if fseek(fid, 1, 'bof') == -1 % empty file
   disp("file is empty");
else
   a = 1;
end

while a == 1
    A = fgetl(fid); % read one line in the file
    A_element = strsplit(A,' '); % split long string into elements
    if strcmp(A_element(2), var_chk)
        for wcnt = 1:numwire
            fgetl(fid);fgetl(fid);fgetl(fid); % ignore 3 lines
            I_array = fgetl(fid);
            I_element = strsplit(I_array,' '); % split long string into elements
            I_temp = [I_temp str2double(I_element(3)) str2double(I_element(4))]; % write data
            fgetl(fid);fgetl(fid); % ignore 3 lines
        end
        cnt = cnt + 1;
        cntvar1 = cntvar1 + 1;
    end
    I_vector = [I_vector;I_temp]; % store data into large matrix
    I_temp = [];
    if cntvar1 == numvar1+1 % to separate every numvar1 configuaration
        I_vector = [I_vector; zeros(1,numwire*2)];
        cntvar1 = 1;
    end
    if cnt > numconf
        break
    end
end

% I_vector

% generate array of load as variables in WIPL-D
step = 5;
R1 = []; 
for b = 1:numvar2
    for c = 1:numvar1
        R_temp = c*step;
        R1 =[R1;R_temp];
    end
    R1 = [R1;0]; % to separate every numvar1 configuaration
end
% R1;
R2 = []; 
for b = 1:numvar1
    R_temp = b*step;
    for c = 1:numvar2
        R2 =[R2;R_temp];
    end
    R2 = [R2;0]; % to separate every numvar1 configuaration
end
% R2;


VR1_sim = sqrt(I_vector(:,3).^2+I_vector(:,4).^2)/1000.*R1;
VR2_sim = sqrt(I_vector(:,5).^2+I_vector(:,6).^2)/1000.*R2;
% VR3_sim = sqrt(I_vector(:,7).^2+I_vector(:,8).^2)/1000.*R1;



data2write = [R1 R2 I_vector/1000 VR1_sim VR2_sim]; %  

writematrix(data2write,filename_save, 'Sheet',1,'Range','A1')

fclose(fid);
close all