% This version is used to extract data from data file generated by WIPL-D
% software. It is applied for one variable only.

clc
clear


% file_path = 'E:\WPT_preparing_papers\Smooth3coilSys\wires';

fid=fopen('..\..\..\..\WPT_research\Smooth3coilSys\wires\Z_parameter\twocoil_Z.ad1'); 


numwire = 11; % number of the wires whose currents need to be extracted
numconf = 2; % number of configurations (loop)
var_chk = 'yr'; % variable changed in WIPL-D
cnt = 1;

Z_vector = [];
Z_temp = [];

filename_save = 'testdata.xlsx';
if isfile(filename_save)
    delete testdata.xlsx
end


if fseek(fid, 1, 'bof') == -1 % empty file
   disp("file is empty");
else
   a = 1;
end

while a == 1
    A = fgetl(fid); % read one line in the file
    A_element = strsplit(A,' '); % split long string into elements
    if strcmp(A_element(2), var_chk)
        fgetl(fid); % ignore next line
        for wcnt = 1:(numwire*numwire)
            Parameters = fgetl(fid); % read the line
            Para_elements = strsplit(Parameters,' '); % split long string into elements
            Z_temp = [Z_temp; str2double(Para_elements(7:8))]; % write data
        end
        cnt = cnt + 1;
    end
    Z_vector = [Z_vector Z_temp]; % store data into large matrix
    Z_temp = [];
    if cnt > numconf
        break
    end
end

Z_vector

n=1:numconf;
coupling = Z_vector(2,2*n)'

writematrix(Z_vector,filename_save, 'Sheet',1,'Range','A1');
writematrix(coupling,filename_save, 'Sheet',1,'Range','A10');

fclose(fid);
fclose('all');